apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-server-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication-server-flask
  template:
    metadata:
      labels:
        app: authentication-server-flask
    spec:
      containers:
      - name: authentication-server-flask
        image: authentication-server-flask:v1
        ports:
        - containerPort: 5000