apiVersion: v1
kind: Service
metadata:
  name: authentication-server-flask-service
spec:
  selector:
    app: authentication-server-flask
  ports:
    - protocol: TCP
      port: 5000 # Puerto expuesto dentro del cluster
      targetPort: 5000 # Puerto en el contenedor Flask
  type: ClusterIP


